- name: Download Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-{{ ansible_architecture }}"
    dest: "{{ docker_compose_path }}"
    mode: '0755'
    force: true
  register: compose_download
  tags: ['docker', 'docker-compose']

- name: Wait for Docker Compose download to complete
  wait_for:
    path: "{{ docker_compose_path }}"
    state: present
  when: compose_download.changed
  tags: ['docker', 'docker-compose']

- name: Create Docker Compose symlink
  file:
    src: "{{ docker_compose_path }}"
    dest: /usr/bin/docker-compose
    state: link
    force: yes
  tags: ['docker', 'docker-compose']